version: '2'
services:
    cloudgw:
        build: cloudgw/
        privileged: true
        tty: true
        stdin_open: true
        networks:
            internet:
                ipv4_address: 10.0.0.254
            cloud:
                ipv4_address: 10.1.0.254
    asrv:
        build: server/
        tty: true
        privileged: true
        stdin_open: true
        volumes:
            - ./server:/app
        networks:
            cloud:
                ipv4_address: 10.1.0.2
    aiot:
        build:
            context: iot/
        tty: true
        stdin_open: true
        privileged: true
        environment:
            - IOT_SERVER=http://10.1.0.2:8080
            - GWNAME=agw
        links:
            - asrv
        networks:
            alan:
    agw:
        build: agw/
        privileged: true
        tty: true
        stdin_open: true
        depends_on:
            - cloudgw
        networks:
            alan:
            internet:
networks:
    internet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
    cloud:
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.0.0/16
                  gateway: 10.1.0.1
    alan:
        driver: bridge
        ipam:
            config:
                - subnet: 10.2.0.0/16
                  gateway: 10.2.0.1
